#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: build-manifest.sh [options]

Generate manifest.json for a Harness release from a directory of built
assets (per-platform CLI binaries + the harness-dist bundle, each with a
.sha256 sidecar). The manifest is machine-readable: a consumer resolves
"what do I download, and is it intact" from this one file.

Never hand-edit manifest.json; it is generated by the release workflow.

Options:
      --version <v>    Release version (e.g. v0.1.13). Defaults to the tag in
                       scripts/harness-cli-release-tag (prefix stripped).
      --dist-dir <d>   Directory holding the built assets. Defaults to dist.
      --notes <text>   Migration / release notes string. Also read from the
                       HARNESS_MIGRATION_NOTES env var. Defaults to "".
      --out <path>     Output path. Defaults to <dist-dir>/manifest.json.
      --check          Verify an existing manifest.json against the assets on
                       disk (checksums + presence), then exit. CI gate.
  -h, --help           Show this help.
EOF
}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
version=""
dist_dir="$repo_root/dist"
notes="${HARNESS_MIGRATION_NOTES:-}"
out=""
mode="build"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version) [ "$#" -ge 2 ] || fail "$1 requires a value"; version="$2"; shift 2 ;;
    --dist-dir) [ "$#" -ge 2 ] || fail "$1 requires a path"; dist_dir="$2"; shift 2 ;;
    --notes) [ "$#" -ge 2 ] || fail "$1 requires a value"; notes="$2"; shift 2 ;;
    --out) [ "$#" -ge 2 ] || fail "$1 requires a path"; out="$2"; shift 2 ;;
    --check) mode="check"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

[ -n "$out" ] || out="$dist_dir/manifest.json"

sha256_of() {
  local file="$1"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{ print $1 }'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{ print $1 }'
  else
    fail "shasum or sha256sum is required"
  fi
}

resolve_version() {
  if [ -n "$version" ]; then printf '%s\n' "$version"; return; fi
  local tag_file="$repo_root/scripts/harness-cli-release-tag" tag=""
  [ -f "$tag_file" ] && tag="$(awk 'NF && $1 !~ /^#/ { print $1; exit }' "$tag_file")"
  [ -n "$tag" ] || fail "Could not resolve version: pass --version or populate scripts/harness-cli-release-tag"
  printf '%s\n' "${tag#harness-cli-}"
}

json_escape() {
  # Escape a string for embedding as a JSON value.
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\t'/\\t}"
  s="${s//$'\r'/}"
  printf '%s' "$s"
}

# Schema migrations shipped in this release, derived from the same installer
# file list the dist bundle is built from (keeps manifest <-> bundle consistent).
schema_migrations() {
  "$repo_root/scripts/build-harness-dist.sh" --list \
    | grep '^scripts/schema/.*\.sql$' \
    | sed 's#^scripts/schema/##' \
    | LC_ALL=C sort
}

# Discover per-platform binary assets in the dist dir (exclude bundle + sidecars).
binary_assets() {
  find "$dist_dir" -maxdepth 1 -type f -name 'harness-cli-*' \
    ! -name '*.sha256' \
    | sed "s#^$dist_dir/##" \
    | LC_ALL=C sort
}

version="$(resolve_version)"

if [ "$mode" = "check" ]; then
  [ -f "$out" ] || fail "Manifest not found: $out"
  command -v python3 >/dev/null 2>&1 || fail "python3 is required for --check"
  DIST_DIR="$dist_dir" python3 - "$out" <<'PY'
import json, os, sys, hashlib
manifest_path = sys.argv[1]
dist = os.environ["DIST_DIR"]
with open(manifest_path) as fh:
    m = json.load(fh)

def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

errors = []
assets = list(m.get("binaries", []))
b = m.get("bundle")
if b:
    assets.append(b)
for a in assets:
    name, want = a["name"], a["sha256"]
    p = os.path.join(dist, name)
    if not os.path.isfile(p):
        errors.append(f"missing asset: {name}")
        continue
    got = sha(p)
    if got != want:
        errors.append(f"checksum mismatch {name}: manifest {want} != disk {got}")

if errors:
    print("Manifest check FAILED:", file=sys.stderr)
    for e in errors:
        print("  " + e, file=sys.stderr)
    sys.exit(1)
print(f"Manifest OK: {len(assets)} assets match their checksums.")
PY
  exit 0
fi

# --- build mode ---
bundle_name="harness-dist-$version.tar.gz"
bundle_path="$dist_dir/$bundle_name"
[ -f "$bundle_path" ] || fail "Dist bundle missing: $bundle_path (run build-harness-dist.sh first)"

binaries="$(binary_assets)"
[ -n "$binaries" ] || fail "No harness-cli-* binaries found in $dist_dir"

migrations="$(schema_migrations)"
schema_count="$(printf '%s\n' "$migrations" | grep -c . || true)"
schema_version="$(printf '%s\n' "$migrations" | tail -1 | sed 's/[^0-9].*//' | sed 's/^0*//')"
[ -n "$schema_version" ] || schema_version=0

generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
bundle_sha="$(sha256_of "$bundle_path")"

# Build JSON by hand (no jq dependency, portable to macOS + Linux runners).
{
  printf '{\n'
  printf '  "schemaVersion": 1,\n'
  printf '  "harnessVersion": "%s",\n' "$(json_escape "$version")"
  printf '  "generatedAt": "%s",\n' "$generated_at"
  printf '  "schema": {\n'
  printf '    "version": %s,\n' "$schema_version"
  printf '    "count": %s,\n' "$schema_count"
  printf '    "migrations": [\n'
  first=1
  while IFS= read -r mig; do
    [ -n "$mig" ] || continue
    [ "$first" -eq 1 ] || printf ',\n'
    printf '      "%s"' "$(json_escape "$mig")"
    first=0
  done <<EOF
$migrations
EOF
  printf '\n    ]\n'
  printf '  },\n'
  printf '  "binaries": [\n'
  first=1
  while IFS= read -r bin; do
    [ -n "$bin" ] || continue
    sha="$(sha256_of "$dist_dir/$bin")"
    # Platform label = binary name minus the "harness-cli-" prefix and .exe.
    plat="${bin#harness-cli-}"; plat="${plat%.exe}"
    [ "$first" -eq 1 ] || printf ',\n'
    printf '    { "platform": "%s", "name": "%s", "sha256": "%s" }' \
      "$(json_escape "$plat")" "$(json_escape "$bin")" "$sha"
    first=0
  done <<EOF
$binaries
EOF
  printf '\n  ],\n'
  printf '  "bundle": { "name": "%s", "sha256": "%s" },\n' \
    "$(json_escape "$bundle_name")" "$bundle_sha"
  printf '  "migrationNotes": "%s"\n' "$(json_escape "$notes")"
  printf '}\n'
} > "$out"

# Validate the JSON we just emitted, when a parser is available.
if command -v python3 >/dev/null 2>&1; then
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$out" \
    || fail "Generated manifest is not valid JSON: $out"
fi

printf 'Wrote %s\n' "$out"
